namespace: "nutanix"
name: "ncp"
version: "1.1.0-beta.1"
readme: "README.md"
authors:
  - "Prem Karat (@premkarat)"
  - "Gevorg Khachatryan (@Gevorg-Khachatryan-97)"
description: Ansible collection for v3 Nutanix APIs https://www.nutanix.dev/api-reference-v3/
license_file: 'LICENSE'
tags: [nutanix, prism, ahv, cloud, infrastructure]
repository: https://github.com/nutanix/nutanix.ansible
documentation: https://nutanix.github.io/nutanix.ansible/
homepage: https://nutanix.github.io/nutanix.ansible/
issues: https://github.com/nutanix/nutanix.ansible/issues
build_ignore: []